##### PREFIX #####
unbind C-b
set -g prefix C-a
bind C-a send-prefix

##### KEYBINDINGS #####
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

bind -r m resize-pane -Z

##### COPY MODE #####
unbind -T copy-mode-vi y
bind -T copy-mode-vi y send -X copy-pipe-and-cancel \
  'sh -c "if command -v wl-copy >/dev/null; then wl-copy; \
          elif command -v pbcopy >/dev/null; then pbcopy; \
          else cat >/dev/null; fi"'
bind -T copy-mode-vi v send -X begin-selection

##### PLUGINS #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

bind-key -T prefix S run-shell "~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh"
bind-key -T prefix R run-shell "~/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh"

run '~/.config/tmux/plugins/tpm/tpm'
