[iCloud]
source = imaps://cannahum%40me.com@imap.mail.me.com:993
source-cred-cmd = bash -lc 'source "$HOME/.config/aerc/secrets.local" && printf "%s" "$ICLOUD_MAIL_APP_PASSWORD"'

outgoing = smtp+plain://cannahum%40me.com@smtp.mail.me.com:587
outgoing-cred-cmd = bash -lc 'source "$HOME/.config/aerc/secrets.local" && printf "%s" "$ICLOUD_MAIL_APP_PASSWORD"'

default = INBOX
from = Can (a.k.a. Jon) Nahum <cannahum@me.com>
copy-to = Sent Messages
archive = Archive
