return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    -- LazyVim's opts_extend = { "ensure_installed" } (declared on its own
    -- spec for this plugin) unions this with its own base list rather than
    -- replacing it, so overlap with LazyVim's own parsers is harmless.
    ensure_installed = {
      "json",
      "javascript",
      "typescript",
      "tsx",
      "yaml",
      "html",
      "css",
      "prisma",
      "markdown",
      "markdown_inline",
      "mermaid",
      "svelte",
      "graphql",
      "bash",
      "lua",
      "vim",
      "dockerfile",
      "gitignore",
      "query",
      "vimdoc",
      "c",
      "go",
      "gomod",
      "java",
      "python",
      "templ",
      "c_sharp",
      "kotlin",
      "zig",
      "proto",
      "sql",
    },
  },
}
