# vim:ft=kitty

## name:     Monokai Pro (Ristretto)
## license:  MIT
## upstream: colors sourced from Omarchy's official ristretto theme
##           (~/.local/share/omarchy/themes/ristretto/colors.toml)
## blurb:    Warm, low-contrast Monokai variant with reddish-brown undertones



# The basic colors
foreground              #E6D9DB
background              #2C2525
selection_foreground    #E6D9DB
selection_background    #403E41

# Cursor colors
cursor                  #C3B7B8
cursor_text_color       #2C2525

# URL underline color when hovering with mouse
url_color               #C3B7B8

# Kitty window border colors
active_border_color     #F38D70
inactive_border_color   #948A8B
bell_border_color       #F9CC6C

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #2C2525
active_tab_background   #F38D70
inactive_tab_foreground #E6D9DB
inactive_tab_background #211C1C
tab_bar_background      #191515

# Colors for marks (marked text in the terminal)
mark1_foreground #2C2525
mark1_background #F38D70
mark2_foreground #2C2525
mark2_background #A8A9EB
mark3_foreground #2C2525
mark3_background #85DACC

# The 16 terminal colors

# black
color0 #72696A
color8 #948A8B

# red
color1 #FD6883
color9 #FF8297

# green
color2  #ADDA78
color10 #C8E292

# yellow
color3  #F9CC6C
color11 #FCD675

# blue
color4  #F38D70
color12 #F8A788

# magenta
color5  #A8A9EB
color13 #BEBFFD

# cyan
color6  #85DACC
color14 #9BF1E1

# white
color7  #E6D9DB
color15 #F1E5E7
